# Generated by Django 3.2 on 2022-06-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_dark',
            field=models.BooleanField(default=False),
        ),
    ]
