# Generated by Django 3.2 on 2022-06-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=models.CharField(max_length=50, verbose_name='question'),
        ),
    ]
