# Generated by Django 3.2 on 2022-06-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='show_custom_message',
            field=models.BooleanField(default=False, verbose_name='Show custom message if student passed or failed'),
        ),
    ]
