# Generated by Django 3.2 on 2022-06-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_show_custom_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='avg_score',
            field=models.CharField(max_length=50, null=True, verbose_name='avg score'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='no_of_score',
            field=models.CharField(max_length=50, null=True, verbose_name='no of score'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='What is the passing score'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=models.CharField(max_length=50, null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='status'),
        ),
    ]
