# Generated by Django 3.2 on 2022-06-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_explanation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_explanation_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_marks',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
