# Generated by Django 3.2 on 2022-06-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_question_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
