# Generated by Django 3.2 on 2022-06-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_result_partial_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('Multiple Choices (choose one)', 'Multiple Choices (choose one)'), ('Multiple Choices (choose many)', 'Multiple Choices (choose many)'), ('True/False', 'True/False'), ('Matching', 'Matching'), ('Fill in the blank', 'Fill in the blank'), ('Essay', 'Essay'), ('Poll', 'Poll'), ('Group', 'Group')], max_length=30, null=True),
        ),
    ]
