# Generated by Django 3.2 on 2022-06-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='student_identifier',
            field=models.TextField(default='please enter your school email address', help_text='What should test takers enter to identify themselves?', verbose_name='student_identifier'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('Multiple Choices (choose one)', 'Multiple Choices (choose one)'), ('Multiple Choices (choose many)', 'Multiple Choices (choose many)'), ('True/False', 'True/False'), ('Matching', 'Matching'), ('Fill in the blank', 'Fill in the blank'), ('Short Question', 'Short Question'), ('Essay', 'Essay'), ('Text Block', 'Text Block'), ('Poll', 'Poll'), ('Group', 'Group')], max_length=30, null=True),
        ),
    ]
